### ISSUE TITLE
As a User, I should be able to create a post

### ISSUE THREAD

**Issue by kenmazaika** [FirehoseCommunity/Lets-Pair-Program#106]
It looks like the page exists, but I can't get there:

http://fhp-lets-pair-program.herokuapp.com/sections/1/posts/new

A link there should exist.

**Comment by kenmazaika** [comment]
It should probably exist in the context of the accordion

**Comment by kenmazaika** [comment]
@cacauzen since you're working on the accordion can you make sure this works

**Comment by cacauzen** [comment]
Link is in the Accordion :)

**Comment by cacauzen** [comment]
This issue has been resolved.
