### ISSUE TITLE
Changing how we list the sections to make less clicking for user

### ISSUE THREAD

**Issue by kenmazaika** [FirehoseCommunity/Lets-Pair-Program#110]
What do you think of listing all the sections on page load, and having the actual post links be in accordions under the sections? I think that would result in less clicking to do for the user. Kind of like this:
![categories-index](https://cloud.githubusercontent.com/assets/3732709/14746496/eb3c5268-087d-11e6-9826-bc104d4aea95.png)

Taken from a comment by @risu-kun

**Comment by amarkpark** [comment]
Please also see PR https://github.com/FirehoseCommunity/Lets-Pair-Program/pull/123 by @cacauzen
