### ISSUE TITLE
Changing where the section links go.

### ISSUE THREAD

**Issue by kenmazaika** [FirehoseCommunity/Lets-Pair-Program#111]
It looks like right now, the Section Title links are directing us to `post_path(section.id)`, which will be the show page for the post with the same id as the section. I don't think that's the behavior you wanted? ;) But this could be resolved by implementing something closer to #110 

This was a suggestion by @risu-kun

**Comment by amarkpark** [comment]
Addressed by @cacauzen in PR #123 and also I think @risu-kun in PR #127
