### ISSUE TITLE
Markdown Editor features MIA (this is both dev and prod)

### ISSUE THREAD

**Issue by amarkpark** [FirehoseCommunity/Lets-Pair-Program#117]
No format buttons, no live preview, and it appears markdown is not being processed.  Markdown was functioning a few days ago.

![screen shot 2016-04-23 at 12 34 22 pm](https://cloud.githubusercontent.com/assets/13741014/14763040/c17581a2-094f-11e6-8b10-845a6bb53c8a.png)

![screen shot 2016-04-23 at 12 33 15 pm](https://cloud.githubusercontent.com/assets/13741014/14763042/c5b0f6de-094f-11e6-8b3d-5920183cdf1a.png)

**Comment by amarkpark** [comment]
This behavior is intermittent. With poking and testing throughout the day @risu-kun and I are as yet unable to reliably reproduce either the presence or absence of the markdown components.

**Comment by risu-kun** [comment]
@cacauzen has determined that the editor only displays upon refreshing the page, and that this quirk is caused by pagedown's interaction with turbolinks. (See https://github.com/hughevans/pagedown-bootstrap-rails/issues/14)

**Comment by risu-kun** [comment]
Apparently we can use jQuery Turbolinks instead: https://github.com/kossnocorp/jquery.turbolinks

**Comment by amarkpark** [comment]
I think @cacauzen's fix will work well at this time, if we experience slow performance that requires caching any pages we can always reenable turbolinks and selectively disable the links to pages with markdown forms, or try @risu-kun's jQuery Turbolinks instead. :-)

**Comment by amarkpark** [comment]
Yeah, so need to actually PR this fix first. D'Oh!

**Comment by kenmazaika** [comment]
My advice is to remove turbolinks entirely.  I'm pretty strongly against that feature of rails, haha.
