### ISSUE TITLE
Planned obsolescence or twilight for old posts?

### ISSUE THREAD

**Issue by amarkpark** [FirehoseCommunity/Lets-Pair-Program#130]
Should we implement some way to automatically end-of-life the old posts?

**Comment by kenmazaika** [comment]
I think if we just sort by created at date and include the created at timestamp on the post, people will have the information they need.  This seems like something we could skip for the initial launch and then get user feedback for.

**Comment by cacauzen** [comment]
Agreed. We can keep contributing to this app, right @kenmazaika? Or will this be closed after you start a new one?

**Comment by kenmazaika** [comment]
Yeah, we can absolutely keep working on it after we launch it.

**Comment by amarkpark** [comment]
Sounds Good
