### ISSUE TITLE
As a User, I should have the ability to be an admin

### ISSUE THREAD

**Issue by kenmazaika** [FirehoseCommunity/Lets-Pair-Program#15]
User database table should have an admin field.  And there should be a way to create the admins.

**Comment by kenmazaika** [comment]
review:

https://github.com/FirehoseCommunity/DEFCON#developer-notes

**Comment by kenmazaika** [comment]
* Add a boolean database field to the `users` table.
* It should be possible to promote a user.  Research using a `rake task` to elevate a user's permissions.

**Comment by kenmazaika** [comment]
Leaving this ticket open, pending on the rake task integration.

**Comment by kenmazaika** [comment]
`rake createUser[kmazaika@gmail.com, whateverPassword]`

**Comment by amarkpark** [comment]
New rake file can add users, admins, and promote and demote users to and from admin.
