### ISSUE TITLE
As an User, I should be able to create new sections

### ISSUE THREAD

**Issue by kenmazaika** [FirehoseCommunity/Lets-Pair-Program#16]
These sections map up to what are on the wireframes for:

* LPP News,
* Introductions
* Meetings / Event.

etc.  Non admins should be able to build these.

**Comment by dvanetten03** [comment]
Non admins should NOT be able to build these.

**Comment by kenmazaika** [comment]
* Build a new form
* Deal with the create action
* Add validations on the section and also ensure the items are valid on creation.

**Comment by kenmazaika** [comment]
We'll lock this down into admin only in a new ticket.

**Comment by kenmazaika** [comment]
I'm going to grab this from you Robert, since you're out for the week.

**Comment by kenmazaika** [comment]
@risu-kun, we can setup a category database too.
