### ISSUE TITLE
As a Developer, I want to have Twitter Bootstrap

### ISSUE THREAD

**Issue by kenmazaika** [FirehoseCommunity/Lets-Pair-Program#17]
Integrate with Twitter Bootstrap so we can use those design elements.

**Comment by kenmazaika** [comment]
I believe @cacauzen integrated with bootstrap because she was blocked on the ticket she was working on.

**Comment by cacauzen** [comment]
Oh, sorry, I didn't see someone else was assigned to do it. In the future, should I take of things anyway of wait to it to be done by the original assignee?

**Comment by kenmazaika** [comment]
No problem.  You were blocked from doing your ticket, until that ticket was completed.  In cases like that you should ask about what to do in the original ticket and offer to help out usually.  No problem here though.
