### ISSUE TITLE
As a User, when I click on an section of the application I should see the posts listed 

### ISSUE THREAD

**Issue by kenmazaika** [FirehoseCommunity/Lets-Pair-Program#20]
I would suggest using the `sections#show` if we have a `sections_controller`, to list out the posts.

**Comment by kenmazaika** [comment]
-> blocked by not having sections in the database.  Once the sections are squared away, feel free to grab this ticket.

**Comment by kenmazaika** [comment]
I believe this is resolved as clicking the button takes us to the page that it should.

**Comment by enico** [comment]
k sounds good!
