### ISSUE TITLE
Static Pages for what is inside the Footer

### ISSUE THREAD

**Issue by kenmazaika** [FirehoseCommunity/Lets-Pair-Program#35]
We need pages for these:

* About Us 
* Contacts 
* Press 
* Terms & Conditions

**Comment by DarthDARKFather** [comment]
Should I just leave them as static or add like background images or a more general idea of what it should look like once someone is assigned to style those pages?

**Comment by kenmazaika** [comment]
It's up to you!  If you want to flesh them out with real text / images, that would be great.  We also could break it into more tickets for someone else to do if you wanted.

**Comment by DarthDARKFather** [comment]
Thanks!

**Comment by DarthDARKFather** [comment]
This issue can now be closed, and maybe open a new issue about adding info to those static pages.
