### ISSUE TITLE
As someone who lands on the splash page, I should be able to opt into the database

### ISSUE THREAD

**Issue by kenmazaika** [FirehoseCommunity/Lets-Pair-Program#38]
To support this, we will need:

**Database Model** -> `OptIn`, use whatever name you choose.
  * email

**Controller Changes** -> we will want to make a new opt in in the controller.

**View: should show the form** -> you may need to integrate with SimpleForm if this is the first form that we are making.

**Comment by enico** [comment]
Quick question here @kenmazaika since we have users signing up etc, should this redirect from a button "Join/Find etc" on the splash page to the signup page? If they are already registered go to the feed/sections page?

**Comment by kenmazaika** [comment]
That makes sense, Erica!  Seems like a reasonable behavior for the application to redirect authenticated users to the feed page.
