### ISSUE TITLE
Footer icons should be smaller.

### ISSUE THREAD

**Issue by kenmazaika** [FirehoseCommunity/Lets-Pair-Program#56]

**Comment by dvanetten03** [comment]
I'm also thinking that pinterest and instagram might not be the right ones to log in for pair programming?  I can see facebook and twitter, but i'm thinking we add github and maybe linkedin?  Maybe not on linkedin, but I don't think the others should be there for this...thoughts?  I'm going to submit with facebook, linkedin, github and twitter and if we need to change, that can be done.

**Comment by dvanetten03** [comment]
Maybe google plus, too?  Since we have that as part of firehose...

**Comment by dvanetten03** [comment]
Ok...no linkedin, the links go to all Firehose pages.

**Comment by dvanetten03** [comment]
I made them smaller and kept them 'muted' until you hover and/or click on them...don't want them to be the focus of the page...thoughts?

**Comment by kenmazaika** [comment]
I think @cacauzen and @enico were thinking more about the design than I am.  What do you think?

**Comment by enico** [comment]
I think github,google+ would be a good addition

**Comment by kenmazaika** [comment]
:+1:

**Comment by dvanetten03** [comment]
This was completed as part of previous commit.
