### ISSUE TITLE
There should be a Database Table for Publicly Requesting Pairing

### ISSUE THREAD

**Issue by kenmazaika** [FirehoseCommunity/Lets-Pair-Program#6]
This should have a few field.

* Description (what do you want to pair program on)
* Availability -> timezones

**Comment by amarkpark** [comment]
Is this intended to act as a simple message board where a user/owner will post a project in the form of text and other users will be able to browse the pairing requests? (Easy implementation) Once the pairing request is answered the post times out or is removed.  Or will these need further functionality as a join table to track pairing metrics later on? (Requires more planning)

And speaking of timing out, might there be an automatic timeout to keep stale posts from cluttering the board if either A) The posting user is no longer active or B) forgets to remove post once it is fulfilled?

**Comment by kenmazaika** [comment]
Out of date ticket.  Closing this out.
