### ISSUE TITLE
Add gravatar feature to User Profile/Dashboard

### ISSUE THREAD

**Issue by NKHolton** [FirehoseCommunity/Lets-Pair-Program#69]
Already added Gravtastic gem but need to fully implement gravatar feature.

**Comment by cacauzen** [comment]
Sweet! I did this for the Grammable app, but not with Gravtastic. Will definitely read up on it, and let me know if you want to do this together! @NKHolton

**Comment by NKHolton** [comment]
Yeah I'd love to work on it together because I don't know where to start!  What did you do for Grammable.  Maybe we can talk in Slack on a time to pair program?

**Comment by kenmazaika** [comment]
@enico can you grab this and maybe have @cacauzen help you with it?
