### ISSUE TITLE
For the categories index we should display them inline with an accordion

### ISSUE THREAD

**Issue by kenmazaika** [FirehoseCommunity/Lets-Pair-Program#75]
Checkout this twitter bootstrap feature, to allow the items on the categories#index page to be listed out.

http://getbootstrap.com/javascript/#collapse

**Comment by cacauzen** [comment]
I'll take this one, if still available :)

**Comment by dvanetten03** [comment]
We are on the call assigning right now.

**Comment by risu-kun** [comment]
Hey Claudia, when you list out the post titles, can you link them to the posts#show page? :smile:

**Comment by cacauzen** [comment]
Deal!

**Comment by cacauzen** [comment]
This issue should be closed as well.

**Comment by amarkpark** [comment]
Resolved with PR #123
