### ISSUE TITLE
Delete customdata.rake

### ISSUE THREAD

**Issue by amarkpark** [FirehoseCommunity/Lets-Pair-Program#91]
I was looking at the rake user tasks and noticing the message I added for explaining the usage was odd.  I think @dvanetten03 may have been working on the rake tasks at the same time I was working on them and we crossed paths.  When I pushed the branch that added all the user tasks the customdata.rake file was empty and now it has a few entries that I believe are actually interfering with the functionality of the rake user tasks.

@kenmazaika I would like to delete this file: https://github.com/FirehoseCommunity/Lets-Pair-Program/blob/master/lib/tasks/customdata.rake to remove the potential for conflicts.

**Comment by kenmazaika** [comment]
Ah, that makes sense.  Works for me, Amanda!

**Comment by amarkpark** [comment]
addressed in PR https://github.com/FirehoseCommunity/Lets-Pair-Program/pull/113
