### ISSUE TITLE
Modals aren't working

### ISSUE THREAD

**Issue by cacauzen** [FirehoseCommunity/Lets-Pair-Program#96]
@risu-kun and I noticed that none of the modals are working in our local environments. Let's fix this!

**Comment by risu-kun** [comment]
![screen shot 2016-04-20 at 11 05 37 am](https://cloud.githubusercontent.com/assets/3732709/14682369/58673da8-06f3-11e6-9edb-6635061a5f3f.png)
screenshot from @amarkpark

**Comment by risu-kun** [comment]
@enico recommended a fix [here](http://stackoverflow.com/questions/10636667/bootstrap-modal-appearing-under-background)

I tried the first solution there, but the problem persists.
