### ISSUE TITLE
Should be a direct link to Session List on TopNav

### ISSUE THREAD

**Issue by amarkpark** [FirehoseCommunity/Lets-Pair-Program#99]
Right now in order to go to the List Categories screen a user has to click on the LPP home link and then click again on the "List Sessions" button front and center.  As that will be the primary use page on the site I think there should be a link to go directly to the categories#index screen from any other page in the site.  Go directly to list from Profile page.  Go directly to list from About page.  Add link to categories_path on  TopNav.

**Comment by kenmazaika** [comment]
![screenshot](https://api.monosnap.com/rpc/file/download?id=7uA91pRdr5bawu4Cl08kJ1NAJoK08u)

**Comment by DarthDARKFather** [comment]
This can now be closed.
